### ISSUE TITLE
Driver request for LSM303AGR

### ISSUE THREAD

**Issue by bodagovsky** [tinygo-org/drivers#147] opened 2020-04-23 07:53 UTC
Here we have MAG3110 driver, but microbit v 1.5 uses LSM303AGR [magnetometer.](https://tech.microbit.org/hardware/i2c/) I'd highly appreciate If you added support for this

**Comment by deadprogram** [comment] 2020-04-24 05:25
This is a duplicate of #125 so closing.

Hopefully someone who has one of the newer Microbit boards can work on this!

**Closed by deadprogram** 2020-04-24 05:25 UTC
Labels: duplicate
